### ISSUE TITLE
example for asynchronous operation

### ISSUE THREAD

**Issue by tbalci** [j6mes/httplib#14]
Can you write a sample use

**Comment by j6mes** [comment]
This sample GET method is async. 
https://github.com/j6mes/httplib/blob/2.0.12/JumpKick.HttpLib/JumpKick.HttpLib.Samples/Form1.cs 

The onProgressedChanged function is called after a block is received asynchronously 
The onSuccess is called on completion. This entire library was designed to be mostly async.
