### ISSUE TITLE
 set the synchronous and asynchronous

### ISSUE THREAD

**Issue by NGY198888** [j6mes/httplib#15]
大神，谢谢你的工作，如果可能，我希望httplib可以自由设置同步异步，并且当异步的时候，主线程可以捕获httplib抛出的异常
God, thank you for your work, if possible, I hope serve protocols can be free to set the synchronous and asynchronous, and when the asynchronous and the main thread can capture serve protocols throws exception

**Comment by j6mes** [comment]
I don't fully understand your comment.

You can catch server exceptions using this method `.OnFail(webexception =>{Console.Write(webexception.Message);})`. If you want, you can throw the webexception safely from that OnFail callback.

At the moment, HttpLib is asynchronous. If you want to return a value from the server, it may be best to use either a mutex or a semaphore.
