### ISSUE TITLE
Headers are not being set.

### ISSUE THREAD

**Issue by gitpc988** [j6mes/httplib#16]
Could you give me a Examples?

I use this code to get data,but server can't receive header!

   Header headers = new Header("customhead","somedata"); 
   Http.Get(url).Headers(headers).OnSuccess(result =>{}).Go();

**Comment by j6mes** [comment]
The header you're passing in is a single header. I haven't implemented that. HttpLib only supports collections in that instance. The method you're probably calling is `RequestBuilder Headers(object header)` which uses reflection to iterate over all fields in the class and creates a header for each of those objects.

HttpLib support headers through either passing in an IDictionary<String,String> or a HeaderProvider which returns a collection of headers. The easiest option(s) would either to make a custom class which implements HeaderProvider (it's only 1 method) or to pass in an anonymous object (new {field="data"}) 

Let me know how you get on. I can add a method to add a single header in the next release. But that could take me a week to get round to doing.

**Comment by gitpc988** [comment]
Thanks for you reply!  For you advise,I use Get method like this:
Http.Get(url).Headers(new{Token="somedata"}).OnSuccess(result =>{}).Go();
and like this 

IDictionary<string, string> headers = new Dictionary<string, string>();
headers["Token"]="data":
Http.Get(url).Headers(headers).OnSuccess(result =>{}).Go();

but the server debug info can't find head!   Am i right?

Look forward to your kind reply! Thank you again!

**Comment by j6mes** [comment]
It's fixed in release 2.0.13.58
Available on nuget and on the 2.0.13 branch.

**Comment by eeve** [comment]
https://msdn.microsoft.com/zh-cn/library/1beth6ct(v=VS.95).aspx

How does a restricted header work?

**Comment by j6mes** [comment]
They're largely untested. I would recommend not setting any of the restricted headers in your own code. They should be set later by the tcp client if needed and are liable to be overwritten by the system if you do set them.
