### ISSUE TITLE
Why did you collect all the requests?

### ISSUE THREAD

**Issue by ghost** [j6mes/httplib#18]

**Comment by j6mes** [comment]
It was a feature one of my customers wanted for a project. I added something similar for the public branch, but I've noted it doesn't really scale very well with millions of requests going through Httplib every day. I've removed stats collection now in 2.0.15

**Comment by ghost** [comment]
Thanks for reply. I'm not against the stats collection feature, but I'm against the back door. It reminds me of the XcodeGhost (see: https://en.wikipedia.org/wiki/XcodeGhost).
