### ISSUE TITLE
how to solve this exception? with exception callback?  or surround by try ... catch ... ?

### ISSUE THREAD

**Issue by chjxidian** [j6mes/httplib#19]
exception content:

System.Net.WebException was unhandled
Message: An unhandled exception of type 'System.Net.WebException' occurred in System.dll
Additional information: Unable to connect to the remote server

**Comment by j6mes** [comment]
Did you try adding a .OnFail() to your builder? 
Can you give me more code to help me better understand what you're trying to do
Also please give me a complete stack trace

**Comment by chjxidian** [comment]
Http.Post("http://" + IP + ":" + Port + "/" + CMD)
                .Body(jsonData)
                .OnSuccess(result =>
                {
                    Console.Write(result);
                    //
                    Hashtable tableResult = JsonConvert.DeserializeObject<Hashtable>(result);
                    if (tableResult.Contains("1"))
                    {
                        MessageBox.Show("查找成功！");
                        updateTrainItemsDel update = new updateTrainItemsDel(updateTrainItems);
                        this.Dispatcher.Invoke(update);
                    }
                })
                .OnFail(webexception =>
                {
                    MessageBox.Show("网络超时，请检查网络连接是否正常！", "获取数据失败");
                }).Go();

**Comment by chjxidian** [comment]
Thanks for your replay.
     I have get the exception: "System.Net.WebException was unhandled Message: An unhandled exception of type 'System.Net.WebException' occurred in System.dll", when I add try{ ... } catch(Exception e){ ... }.
     Please tell me the reason.

**Comment by j6mes** [comment]
Thanks. I'll look into it. It looks like it might be a bug in my code.

Does the server return a response with HTTP status code 200? 

Please trying making the request using a tool like postman or advanced rest client and tell me what the status code is. Or if the request times out.

**Comment by j6mes** [comment]
To help me, please also print the full stack trace, this tells me what part of the code is raising the exception: https://stackoverflow.com/questions/4272579/how-to-print-full-stack-trace-in-exception

**Comment by chjxidian** [comment]
I find another bug: 
System.NullReferenceException occurred
  _HResult=-2147467261
  _message=Object reference not set to an instance of an object.
  HResult=-2147467261
  IsTransient=false
  Message=Object reference not set to an instance of an object.
  Source=JumpKick.HttpLib
  StackTrace:
       at JumpKick.HttpLib.Provider.FormBodyProvider.SerializeQueryString(Object parameters)
  InnerException:

**Comment by chjxidian** [comment]
a null reference exception, for what???

**Comment by chjxidian** [comment]
the former bug because of timeout.

**Comment by chjxidian** [comment]
I think it should throw the exception in the onFail() methoid when the request timeout.

**Comment by chjxidian** [comment]
Please help me!

**Comment by chjxidian** [comment]
I have get the message in output tab:
A first chance exception of type 'System.Net.Sockets.SocketException' occurred in System.dll
A first chance exception of type 'System.Net.WebException' occurred in System.dll
A first chance exception of type 'System.Net.WebException' occurred in System.dll
A first chance exception of type 'System.Net.WebException' occurred in System.dll

**Comment by chjxidian** [comment]
Hi, does the timeout exception has been fixed, I concern it day and day. please help me.

**Comment by j6mes** [comment]
The information you've provided doesnt really help me investigate. I've tried to reproduce with no luck.

AFAIK, the webexceptions should all be caught by the onFail handler and i've checked this is the case. 

with the error you're getting on the formbody serializer. the serialiser should handle null values ok, and there's tests to show this. it will also throw an argumentnullexception if you're trying to serialise a null object too. 

the issue could be in the object you're trying to serialize. if any of the property getters in your object throw a null reference exception, it could break and result in a TargetInvokationException, with the innerexception being any exception thrown in your getter.

        public class TestObject
        {
            public String a { get { throw new NullReferenceException("test");} }
            public int b { get { return 0;  } }
        }

        [TestMethod] <--Will throw a targetinvokationexception bubbling up any exception from the getter property. 
        public void TestSerializeObjectWithNullValue()
        {
            FormBodyProvider.SerializeQueryString(new TestObject());
        }

i need much more information if you want me to help.

**Comment by j6mes** [comment]
Try using the library from the branch HttpLib-19 and see if that works: download here -https://ci.appveyor.com/project/j6mes/httplib/build/HttpLib-19.68/artifacts

**Comment by chjxidian** [comment]
Hi, I have try the HttpLib-19 version, but it still throw the excepyion when the request is timeout :

System.Net.WebException was unhandled
Message: An unhandled exception of type 'System.Net.WebException' occurred in System.dll
Additional information: Unable to connect to the remote server

The system out in the output tab is:

A first chance exception of type 'System.Net.Sockets.SocketException' occurred in System.dll
A first chance exception of type 'System.Net.WebException' occurred in System.dll
A first chance exception of type 'System.Net.WebException' occurred in System.dll
A first chance exception of type 'System.Net.WebException' occurred in System.dll

**Comment by chjxidian** [comment]
The exception was throw when run the function in Call Stack:

 >	System.dll!System.Net.ServicePoint.ConnectSocketCallback(System.IAsyncResult asyncResult)	Unknown

**Comment by chjxidian** [comment]
Please check it and help me to find the bug in code.

**Comment by j6mes** [comment]
I can't reproduce this at all so I will close.

Just a quick question though. Does you message box show?
Do you see this?   MessageBox.Show("网络超时，请检查网络连接是否正常！", "获取数据失败");

**Comment by chjxidian** [comment]
Never show the MessageBox，did you give me a email, I can give you the project now.

**Comment by chjxidian** [comment]
I upload the project to net disk, and I share it with you.

链接：http://pan.baidu.com/s/1c1Bi5dY 密码：im6z

**Comment by chjxidian** [comment]
link: http://pan.baidu.com/s/1c1Bi5dY          passwork:im6z

**Comment by chjxidian** [comment]
Link: http://pan.baidu.com/s/1c1Bi5dY         Password: im6z

**Comment by chjxidian** [comment]
IDE version is "VisualStudio 2013"
