### ISSUE TITLE
\n or \r\n

### ISSUE THREAD

**Issue by daixian** [j6mes/httplib#23]
When I upload a file , I got an error on my server(spring boot 1.5.9 / windows server 2012) :
> Header section has more than 10240 bytes (maybe it is not properly terminated).

It is not properly terminated, I replaced all “\n” in the MultipartBodyProvider file with “\r\n”. It worked.
maybe better to use "\r\n" .

**Comment by j6mes** [comment]
Hi, yes. I've just checked RFC2046 and the standard is a CRLF. Could you please make a pull request with your \r\n change and I'll merge it?
