### ISSUE TITLE
SettableActionProvider constructs have problems

### ISSUE THREAD

**Issue by hucongquan** [j6mes/httplib#34]
` private NonActionProvider nonaction = new NonActionProvider();

        public SettableActionProvider(Action<WebHeaderCollection, Stream> success, Action<WebException> fail, Action<HttpWebRequest> make = null)
        {
            if (success == null)
            {
                this.success = nonaction.Success;
            }
            if (fail == null)
            {
                this.fail = nonaction.Fail;
            }  
            if (make == null)
            {
                this.make = nonaction.Make;
            }

            this.success = success;
            this.fail = fail;
            this.make = make;
        }
`
delegate success/fail/make ,although the default value is assigned, it will eventually be replaced by null;

I think the better way may like this:
      ` private NonActionProvider nonaction = new NonActionProvider();

        public SettableActionProvider(Action<WebHeaderCollection, Stream> success, Action<WebException> fail, Action<HttpWebRequest> make = null)
        {
            this.success = success;
            this.fail = fail;
            this.make = make;

            if (success == null)
            {
                this.success = nonaction.Success;
            }
            if (fail == null)
            {
                this.fail = nonaction.Fail;
            }  
            if (make == null)
            {
                this.make = nonaction.Make;
            }
        }`

**Comment by hucongquan** [comment]
@j6mes

**Comment by j6mes** [comment]
Can you send a pull request?

**Comment by hucongquan** [comment]
> @j6mes

Sound good, but haven't write  permissions to the repository.  also can't fork 2.0.16.83

**Comment by hucongquan** [comment]
![image](https://user-images.githubusercontent.com/10986908/60692153-27090200-9f07-11e9-8e16-f5bdbcd74c1a.png)

**Comment by hucongquan** [comment]
Hi @j6mes , new pull request #35.

**Comment by hucongquan** [comment]
fixed by #37
